import { Transaction } from './types';

export const CATEGORIES = [
    { name: 'Pemasukan', color: 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/50 dark:text-emerald-300' },
    { name: 'Kebutuhan Pokok', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-300' },
    { name: 'Tagihan', color: 'bg-orange-100 text-orange-800 dark:bg-orange-900/50 dark:text-orange-300' },
    { name: 'Cicilan', color: 'bg-red-100 text-red-800 dark:bg-red-900/50 dark:text-red-300' },
    { name: 'Hiburan', color: 'bg-purple-100 text-purple-800 dark:bg-purple-900/50 dark:text-purple-300' },
    { name: 'Tabungan', color: 'bg-teal-100 text-teal-800 dark:bg-teal-900/50 dark:text-teal-300' },
    { name: 'Lainnya', color: 'bg-zinc-100 text-zinc-800 dark:bg-zinc-700 dark:text-zinc-300' },
];

export const INITIAL_DATA: Transaction[] = [
    { id: 1, date: "10-Feb", description: "TAMBAHAN UANG (REJEKI)", category: "Pemasukan", planIncome: 6650000, planExpense: 0, actIncome: 6650000, actExpense: 0 },
    { id: 2, date: "28-Feb", description: "Biaya Hidup Sisa Feb", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 600000, actIncome: 0, actExpense: 773377 },
    { id: 3, date: "28-Feb", description: "Gaji Februari (UMK 2026)", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 4, date: "28-Feb", description: "Jatah Hidup MARET", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 1224000, actIncome: 0, actExpense: 0 },
    { id: 5, date: "05-Mar", description: "Bayar Arisan (Maret)", category: "Tagihan", planIncome: 0, planExpense: 400000, actIncome: 0, actExpense: 0 },
    { id: 6, date: "06-Mar", description: "Cicilan Motor (1/23)", category: "Cicilan", planIncome: 0, planExpense: 750000, actIncome: 0, actExpense: 0 },
    { id: 7, date: "07-Mar", description: "THR (1x Gaji)", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 8, date: "08-Mar", description: "Biaya Hari Raya", category: "Hiburan", planIncome: 0, planExpense: 1000000, actIncome: 0, actExpense: 0 },
    { id: 9, date: "10-Mar", description: "Trip Gunung Raung", category: "Hiburan", planIncome: 0, planExpense: 700000, actIncome: 0, actExpense: 0 },
    { id: 10, date: "11-Mar", description: "SPinjam (6/12)", category: "Cicilan", planIncome: 0, planExpense: 564000, actIncome: 0, actExpense: 0 },
    { id: 11, date: "11-Mar", description: "ShopeePayLater (Tagihan Feb)", category: "Cicilan", planIncome: 0, planExpense: 884904, actIncome: 0, actExpense: 0 },
    { id: 12, date: "11-Mar", description: "Honest Card", category: "Cicilan", planIncome: 0, planExpense: 500000, actIncome: 0, actExpense: 0 },
    { id: 13, date: "11-Mar", description: "Tokopedia Card", category: "Cicilan", planIncome: 0, planExpense: 250000, actIncome: 0, actExpense: 0 },
    { id: 14, date: "28-Mar", description: "Gaji Maret", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 15, date: "28-Mar", description: "Jatah Hidup APRIL", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 1224000, actIncome: 0, actExpense: 0 },
    { id: 16, date: "05-Apr", description: "Bayar Arisan (April)", category: "Tagihan", planIncome: 0, planExpense: 400000, actIncome: 0, actExpense: 0 },
    { id: 17, date: "06-Apr", description: "Cicilan Motor (2/23)", category: "Cicilan", planIncome: 0, planExpense: 750000, actIncome: 0, actExpense: 0 },
    { id: 18, date: "11-Apr", description: "SPinjam (7/12)", category: "Cicilan", planIncome: 0, planExpense: 564000, actIncome: 0, actExpense: 0 },
    { id: 19, date: "11-Apr", description: "ShopeePayLater (Tagihan Mar)", category: "Cicilan", planIncome: 0, planExpense: 621591, actIncome: 0, actExpense: 0 },
    { id: 20, date: "11-Apr", description: "Honest Card", category: "Cicilan", planIncome: 0, planExpense: 500000, actIncome: 0, actExpense: 0 },
    { id: 21, date: "11-Apr", description: "Tokopedia Card", category: "Cicilan", planIncome: 0, planExpense: 250000, actIncome: 0, actExpense: 0 },
    { id: 22, date: "28-Apr", description: "Gaji April", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 23, date: "28-Apr", description: "Jatah Hidup MEI", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 1224000, actIncome: 0, actExpense: 0 },
    { id: 24, date: "05-May", description: "Bayar Arisan (Mei)", category: "Tagihan", planIncome: 0, planExpense: 400000, actIncome: 0, actExpense: 0 },
    { id: 25, date: "06-May", description: "Cicilan Motor (3/23)", category: "Cicilan", planIncome: 0, planExpense: 750000, actIncome: 0, actExpense: 0 },
    { id: 26, date: "11-May", description: "SPinjam (8/12)", category: "Cicilan", planIncome: 0, planExpense: 564000, actIncome: 0, actExpense: 0 },
    { id: 27, date: "11-May", description: "ShopeePayLater (Tagihan Apr)", category: "Cicilan", planIncome: 0, planExpense: 514648, actIncome: 0, actExpense: 0 },
    { id: 28, date: "11-May", description: "Honest Card", category: "Cicilan", planIncome: 0, planExpense: 500000, actIncome: 0, actExpense: 0 },
    { id: 29, date: "11-May", description: "Tokopedia Card", category: "Cicilan", planIncome: 0, planExpense: 250000, actIncome: 0, actExpense: 0 },
    { id: 30, date: "28-May", description: "Gaji Mei", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 31, date: "28-May", description: "Jatah Hidup JUNI", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 1224000, actIncome: 0, actExpense: 0 },
    { id: 32, date: "05-Jun", description: "Bayar Arisan (Juni)", category: "Tagihan", planIncome: 0, planExpense: 400000, actIncome: 0, actExpense: 0 },
    { id: 33, date: "06-Jun", description: "Cicilan Motor (4/23)", category: "Cicilan", planIncome: 0, planExpense: 750000, actIncome: 0, actExpense: 0 },
    { id: 34, date: "11-Jun", description: "SPinjam (9/12)", category: "Cicilan", planIncome: 0, planExpense: 564000, actIncome: 0, actExpense: 0 },
    { id: 35, date: "11-Jun", description: "ShopeePayLater (Tagihan Mei)", category: "Cicilan", planIncome: 0, planExpense: 508960, actIncome: 0, actExpense: 0 },
    { id: 36, date: "11-Jun", description: "Honest Card", category: "Cicilan", planIncome: 0, planExpense: 500000, actIncome: 0, actExpense: 0 },
    { id: 37, date: "11-Jun", description: "Tokopedia Card", category: "Cicilan", planIncome: 0, planExpense: 250000, actIncome: 0, actExpense: 0 },
    { id: 38, date: "28-Jun", description: "Gaji Juni", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 39, date: "28-Jun", description: "Jatah Hidup JULI", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 1224000, actIncome: 0, actExpense: 0 },
    { id: 40, date: "05-Jul", description: "Bayar Arisan (Juli)", category: "Tagihan", planIncome: 0, planExpense: 400000, actIncome: 0, actExpense: 0 },
    { id: 41, date: "06-Jul", description: "Cicilan Motor (5/23)", category: "Cicilan", planIncome: 0, planExpense: 750000, actIncome: 0, actExpense: 0 },
    { id: 42, date: "11-Jul", description: "SPinjam (10/12)", category: "Cicilan", planIncome: 0, planExpense: 564000, actIncome: 0, actExpense: 0 },
    { id: 43, date: "11-Jul", description: "ShopeePayLater (Tagihan Jun)", category: "Cicilan", planIncome: 0, planExpense: 408955, actIncome: 0, actExpense: 0 },
    { id: 44, date: "11-Jul", description: "Honest Card", category: "Cicilan", planIncome: 0, planExpense: 500000, actIncome: 0, actExpense: 0 },
    { id: 45, date: "11-Jul", description: "Tokopedia Card", category: "Cicilan", planIncome: 0, planExpense: 250000, actIncome: 0, actExpense: 0 },
    { id: 46, date: "15-Jul", description: "Uang PKWT Cair (1x Gaji)", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 47, date: "28-Jul", description: "Gaji Juli", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 48, date: "28-Jul", description: "Jatah Hidup AGUSTUS", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 1224000, actIncome: 0, actExpense: 0 },
    { id: 49, date: "05-Aug", description: "Bayar Arisan (Agustus)", category: "Tagihan", planIncome: 0, planExpense: 400000, actIncome: 0, actExpense: 0 },
    { id: 50, date: "06-Aug", description: "Cicilan Motor (6/23)", category: "Cicilan", planIncome: 0, planExpense: 750000, actIncome: 0, actExpense: 0 },
    { id: 51, date: "11-Aug", description: "SPinjam (11/12)", category: "Cicilan", planIncome: 0, planExpense: 564000, actIncome: 0, actExpense: 0 },
    { id: 52, date: "11-Aug", description: "ShopeePayLater (Tagihan Jul)", category: "Cicilan", planIncome: 0, planExpense: 308967, actIncome: 0, actExpense: 0 },
    { id: 53, date: "11-Aug", description: "Honest Card", category: "Cicilan", planIncome: 0, planExpense: 500000, actIncome: 0, actExpense: 0 },
    { id: 54, date: "11-Aug", description: "Tokopedia Card", category: "Cicilan", planIncome: 0, planExpense: 250000, actIncome: 0, actExpense: 0 },
    { id: 55, date: "28-Aug", description: "Gaji Agustus", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 56, date: "28-Aug", description: "Jatah Hidup SEPTEMBER", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 1224000, actIncome: 0, actExpense: 0 },
    { id: 57, date: "05-Sep", description: "Bayar Arisan (September)", category: "Tagihan", planIncome: 0, planExpense: 400000, actIncome: 0, actExpense: 0 },
    { id: 58, date: "06-Sep", description: "Cicilan Motor (7/23)", category: "Cicilan", planIncome: 0, planExpense: 750000, actIncome: 0, actExpense: 0 },
    { id: 59, date: "11-Sep", description: "SPinjam (12/12 - LUNAS)", category: "Cicilan", planIncome: 0, planExpense: 563996, actIncome: 0, actExpense: 0 },
    { id: 60, date: "11-Sep", description: "ShopeePayLater (Tagihan Agu)", category: "Cicilan", planIncome: 0, planExpense: 43620, actIncome: 0, actExpense: 0 },
    { id: 61, date: "11-Sep", description: "Honest Card", category: "Cicilan", planIncome: 0, planExpense: 500000, actIncome: 0, actExpense: 0 },
    { id: 62, date: "11-Sep", description: "Tokopedia Card", category: "Cicilan", planIncome: 0, planExpense: 250000, actIncome: 0, actExpense: 0 },
    { id: 63, date: "28-Sep", description: "Gaji September", category: "Pemasukan", planIncome: 3802862, planExpense: 0, actIncome: 0, actExpense: 0 },
    { id: 64, date: "28-Sep", description: "Jatah Hidup OKTOBER", category: "Kebutuhan Pokok", planIncome: 0, planExpense: 1224000, actIncome: 0, actExpense: 0 }
];